parameters:
#    profiler_demo.example.class: Profiler\DemoBundle\Example

services:
#    profiler_demo.example:
#        class: %profiler_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
